#!/bin/bash

here="$(dirname "${0}")"
cd "${here}/post-commit.d" || exit

for hook in *; do
  bash ${hook}
  RESULT=$?
  if [ ${RESULT} != 0 ]; then
    echo "post-commit.d/${hook} returned non-zero: ${RESULT}, abort commit"
    exit $RESULT
  fi
done

exit 0
